# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7ae33864bda1c0d64cd118496212a3db997240e7457d72b8209c2b7d7a268e88380345df67ea5f8d7d3523ce72c5aa4b9ed6683758a202aa8eec75f8827b7d4

test:
  secret_key_base: cb343ab94592d973ef5d6065ce4a2d7656b04d63ee131ae3cb85a82e71c23d3ffb2a3f1fa3070aa95f728c20132bb558d2c86da9e68a5230794a2d4aaeb93563

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
